### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by lqaqlaaa** [roiniti/Formidable-Mod-Loader#1] opened 2024-03-02 03:53 UTC
![Screenshot_2024-03-02-11-49-08-213_bin mt plus](https://github.com/roiniti/Formidable-Mod-Loader/assets/107952122/cc9154be-ddff-4777-8784-fbb377081bcb)
![Screenshot_2024-03-02-11-48-32-232_bin mt plus](https://github.com/roiniti/Formidable-Mod-Loader/assets/107952122/e574942c-9860-4575-80c0-b670f18bbe24)

我在修改后再游戏登录时崩溃，我没有电脑，我不知道哪里出现错误，请帮助我，谢谢

**Comment by roiniti** [comment] 2024-03-03 18:58
I dont full understand your problem, i used the translator because i dont know chinese but i'll try my best to solve your problem, 
The screenshots you send are correct, you say that you dont have a computer, how you installed the libFormidableML.so? also which version of azur lane are you using, AzurLane EN or AzurLane CN? i only tested the modloader in AzurLane EN and if need that info to recreate the error

**Comment by lqaqlaaa** [comment] 2024-03-04 04:43
> 我不完全理解你的问题，我使用翻译器，因为我不懂中文，但我会尽力解决你的问题， 你发送的屏幕截图是正确的，你说你没有电脑，你如何安装libFormidableML。所以？另外，您使用的是哪个版本的 azur Lane，AzurLane EN 还是 AzurLane CN？我只在 AzurLane EN 中测试了 modloader，如果需要该信息来重新创建错误

I used the translator.
I downloaded libFormidableML.zip from Releases and modified it manually.
I used AzurLane CN and it looks like he is different from AzurLane EN

**Comment by lqaqlaaa** [comment] 2024-03-04 04:46
> 我不明白你的问题，我使用翻译器，因为我不懂中文，但我会尽力完全解决你的问题， 你发送的屏幕截图是正确的，你说你没有电脑，你如何安装libFormidableML。所以？另外，您使用的是哪个版本的 azur Lane，AzurLane EN 还是 AzurLane CN？我只在 AzurLane EN 中测试了 modloader，如果需要该信息来重新创建错误

I used the translator.
I downloaded libFormidableML.zip from Releases and modified it manually.
I used AzurLane CN, which looks different from AzurLane EN.

The game crashes after I log into my account

**Comment by roiniti** [comment] 2024-03-05 12:48
Ok, maybe the problem is with the Chinese client in 2-3 week i have time to test it and try to fix it.
Can you execute `logcat -s values` and give me the output? I normally execute it via adb but i think you can download an app to access the logcat, you need to execute it before opening the app, then open the app until crash and send me the output

**Comment by roiniti** [comment] 2024-04-25 19:45
I just tested and version 0.1.1 of the modloader works correctly (with BetterFPSControll mod installed) on the server that I think is the Chinese one (com.hkmanjuu.azurlane.gp) apk version 7.2.9, so I'll close the issue, if you still have problems feel free to open again the issue, or if you prefere, join the discord to send me the apk or debug info

**Closed as completed by roiniti** 2024-04-25 19:45 UTC
